
FROM debian:latest

RUN apt update && apt upgrade && apt install -y \
	mariadb-server

COPY conf/50-server.cnf /etc/mysql/mariadb.conf.d/.
COPY conf/init.sql /etc/mysql/init.sql
COPY script.sh .
# COPY conf/50-server.cnf /etc/mysql/mariadb.conf.d/.
# COPY conf/init.sql /etc/mysql/init.sql
# COPY conf/script.sh .

RUN mkdir /run/mysqld && chmod +x script.sh

CMD ["./script.sh"]
# CMD ["./conf/script.sh"]
